Lint/NestedMethodDefinition:
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'test/**/*'
Style/StringLiterals:
  EnforcedStyle: double_quotes
