Lint/NestedMethodDefinition:
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Max: 19.05
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Max: 28
Style/AccessModifierDeclarations:
  Enabled: false
Style/Documentation:
  Enabled: false
