Lint/NestedMethodDefinition:
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Max: 22.38
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Max: 33
Style/AccessModifierDeclarations:
  Enabled: false
