module Structure
  interface _StructuredDataClass
    def __structure_meta__: () -> {
      attributes: Array[Symbol],
      types: Hash[Symbol, untyped],
      defaults: Hash[Symbol, untyped]
    }
    def parse: (?Hash[String | Symbol, untyped] data, **untyped kwargs) -> instance
  end

  module ClassMethods
    def parse: (?Hash[String | Symbol, untyped] data, **untyped kwargs) -> instance
  end

  def self.new: () ?{ (Structure::Builder) [self: Structure::Builder] -> void } -> untyped
end
