module Structure
  module Types
    BOOLEAN_TRUTHY: Array[untyped]

    self.@boolean: Proc
    self.@kernel_cache: Hash[untyped, Proc]
    self.@parseable_cache: Hash[untyped, Proc]

    def self.coerce: (untyped type, ?untyped? context_class) -> untyped
    def self.resolve_class: (String class_name, untyped? context_class) -> untyped

    private def self.boolean: () -> Proc
    private def self.self_referential: () -> Proc
    private def self.string_class: (String class_name, untyped? context_class) -> Proc
    private def self.array: (untyped element_type, ?untyped? context_class) -> Proc
    private def self.parseable: (untyped type) -> Proc
    private def self.kernel: (Class type) -> Proc
    private def self.parse: (untyped val) -> untyped
  end
end
