module Structure
  module Types
    BOOLEAN_TRUTHY: Array[untyped]

    self.@boolean: Proc

    def self.coerce: (untyped type) -> untyped

    private def self.boolean: () -> Proc
    private def self.self_referential: () -> Proc
    private def self.array: (untyped type) -> Proc
    private def self.parseable: (untyped type) -> Proc
    private def self.kernel: (Class type) -> Proc
    private def self.parse: (untyped val) -> untyped
  end
end
